### ISSUE TITLE
License of the dataset?

### ISSUE THREAD

**Issue by gregwebs** [Percona-Lab/ontime-airline-performance#4]
Can we put license information in the README. Do you know of the license of this dataset? If not I will try to ask BTS.

**Comment by vadimtk** [comment]
I do not know what is the license.

**Comment by gregwebs** [comment]
Thanks, I am asking DOT...

**Comment by gregwebs** [comment]
Officially there is no license.

**Comment by vadimtk** [comment]
I propose we consider the data under PUBLIC DOMAIN, it is from a government website anyway

**Comment by gregwebs** [comment]
According to [Wikipedia](https://en.wikipedia.org/wiki/Copyright_status_of_works_by_the_federal_government_of_the_United_States) it should be in the public domain in the united states but it may not be in other countries.
